# Databricks notebook source
# MAGIC %md
# MAGIC # 🗄️ Activity 2: Create Copilot Tables + Config
# MAGIC
# MAGIC **Goal**: Create the Delta tables and define reusable prompt constants.
# MAGIC
# MAGIC **Tasks**:
# MAGIC - 2.1 — Verify schema: `emobility-uc-dev`.`sandbox-emobility`
# MAGIC - 2.2 — Create `copilot_knowledge_chunks` table
# MAGIC - 2.3 — Create `copilot_conversations` table
# MAGIC - 2.4 — Define agent prompts as Python constants (callable from other notebooks)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.1 — Verify Schema Exists

# COMMAND ----------

# MAGIC %sql
# MAGIC DESCRIBE SCHEMA `emobility-uc-dev`.`sandbox-emobility`;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.2 — Create `copilot_knowledge_chunks` Table

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS `emobility-uc-dev`.`sandbox-emobility`.copilot_knowledge_chunks (
# MAGIC     -- Identity
# MAGIC     chunk_id            STRING          COMMENT 'UUID for each chunk',
# MAGIC     content             STRING          COMMENT 'The actual text content of this chunk',
# MAGIC     content_hash        STRING          COMMENT 'SHA-256 hash of content — for deduplication on re-ingestion',
# MAGIC
# MAGIC     -- Embedding
# MAGIC     embedding           ARRAY<FLOAT>    COMMENT '1024-dim vector embedding (BGE-large)',
# MAGIC
# MAGIC     -- Structured metadata (powers structured-first retrieval)
# MAGIC     source_type         STRING          COMMENT 'doc_generator | kt_transcript',
# MAGIC     source_name         STRING          COMMENT 'Source system: driivz | enovos | spirii | uberall',
# MAGIC     document_type       STRING          COMMENT 'source_overview | notebook_doc | kt_transcript',
# MAGIC     data_layer          STRING          COMMENT 'landing | raw | euh | NULL (for source overviews / api definitions)',
# MAGIC     notebook_name       STRING          COMMENT 'Name of the notebook this chunk belongs to (e.g. landing_etl_uberall_api)',
# MAGIC
# MAGIC     -- Content metadata
# MAGIC     section_header      STRING          COMMENT 'Section: path | notebook_purpose | data_layer | column_transformations | transformation_steps | business_rules | deduplication_logic | join_logic | error_handling',
# MAGIC     tables_mentioned    ARRAY<STRING>   COMMENT 'Table names referenced in this chunk',
# MAGIC     keywords            ARRAY<STRING>   COMMENT 'Top-10 extracted keywords for hybrid search',
# MAGIC
# MAGIC     -- Source tracking
# MAGIC     source_file_path    STRING          COMMENT 'Full Volume path of the source file',
# MAGIC     chunk_index         INT             COMMENT 'Position of this chunk within the source document (0-based)',
# MAGIC     total_chunks        INT             COMMENT 'Total number of chunks from this source document',
# MAGIC
# MAGIC     -- Timestamps
# MAGIC     created_at          TIMESTAMP       COMMENT 'When this chunk was ingested',
# MAGIC     updated_at          TIMESTAMP       COMMENT 'When this chunk was last updated'
# MAGIC )
# MAGIC USING DELTA
# MAGIC COMMENT 'Knowledge chunks for DataPlatform Copilot RAG — enriched with structured metadata for deterministic retrieval'
# MAGIC TBLPROPERTIES (
# MAGIC     'delta.enableChangeDataFeed' = 'true',
# MAGIC     'delta.autoOptimize.optimizeWrite' = 'true',
# MAGIC     'delta.autoOptimize.autoCompact' = 'true'
# MAGIC );

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.3 — Create `copilot_conversations` Table

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS `emobility-uc-dev`.`sandbox-emobility`.copilot_conversations (
# MAGIC     -- Session
# MAGIC     conversation_id     STRING          COMMENT 'Unique session ID',
# MAGIC     turn_number         INT             COMMENT 'Turn number within this conversation (1-based)',
# MAGIC
# MAGIC     -- Query & Response
# MAGIC     user_query          STRING          COMMENT 'The user''s question',
# MAGIC     intent_classified   STRING          COMMENT 'STRUCTURED_QUERY | KNOWLEDGE_LOOKUP | PIPELINE_STATUS | SQL_REVIEW | HYBRID',
# MAGIC     agent_used          STRING          COMMENT 'Which agent handled this: knowledge | genie | pipeline | sql_advisor',
# MAGIC     response_text       STRING          COMMENT 'The full response text returned to the user',
# MAGIC     retrieval_method    STRING          COMMENT 'structured | vector | hybrid | genie',
# MAGIC
# MAGIC     -- Sources
# MAGIC     sources_used        ARRAY<STRING>   COMMENT 'Source references cited in the response',
# MAGIC     sql_generated       STRING          COMMENT 'SQL generated by Genie (NULL if not applicable)',
# MAGIC
# MAGIC     -- Quality metrics
# MAGIC     confidence_score    DOUBLE          COMMENT 'Response Composer confidence (0.0 to 1.0)',
# MAGIC     feedback            STRING          COMMENT 'positive | negative | NULL',
# MAGIC     feedback_comment    STRING          COMMENT 'Optional user feedback text',
# MAGIC
# MAGIC     -- Cost tracking
# MAGIC     model_used          STRING          COMMENT 'Which LLM model was used for final synthesis',
# MAGIC     token_count_in      INT             COMMENT 'Total input tokens consumed',
# MAGIC     token_count_out     INT             COMMENT 'Total output tokens consumed',
# MAGIC     latency_ms          INT             COMMENT 'End-to-end response latency in milliseconds',
# MAGIC
# MAGIC     -- User context
# MAGIC     user_role           STRING          COMMENT 'BA | Engineer | Leadership',
# MAGIC
# MAGIC     -- Timestamps
# MAGIC     created_at          TIMESTAMP       COMMENT 'When this turn was created'
# MAGIC )
# MAGIC USING DELTA
# MAGIC COMMENT 'Conversation history for DataPlatform Copilot — multi-turn context and analytics'
# MAGIC TBLPROPERTIES (
# MAGIC     'delta.enableChangeDataFeed' = 'true',
# MAGIC     'delta.autoOptimize.optimizeWrite' = 'true',
# MAGIC     'delta.autoOptimize.autoCompact' = 'true'
# MAGIC );

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2.4 — Agent Prompts (Python Constants)
# MAGIC
# MAGIC All prompts defined here as constants. Import or copy these into whichever notebook needs them.

# COMMAND ----------

# ─────────────────────────────────────────────────────
# AGENT PROMPTS — reusable constants
# ─────────────────────────────────────────────────────

KNOWLEDGE_AGENT_PROMPT = """You are the Knowledge Agent for the eMobility DataPlatform Copilot.

Your role: Answer questions about data pipelines, transformations, business rules, and architecture using documentation and KT transcripts.

You have access to documentation covering these source systems:
- Driivz: Charging session data, station management
- Enovos: Energy supplier data
- Spirii: Charging network data
- Uberall: Location/listing management data

Data layers in the platform:
- Landing: Raw API responses / file ingestion (as-is from source)
- Raw: Cleaned, typed, deduplicated version of landing data
- EUH: Enterprise Unified Hub — transformed, enriched, business-ready tables

Each source system has these documented notebooks:
1. API definition notebook (e.g., uberall.py)
2. Landing ETL notebook (e.g., landing_etl_uberall_api)
3. Raw ETL notebook (e.g., raw_etl_uberall_api)
4. EUH ETL notebook (e.g., euh_etl_uberall_api)

Each notebook doc covers: path, purpose, data layer, column-level transformations, transformation steps, business rules & hardcoded values, deduplication logic, join logic, error handling & data quality.

When answering:
1. Be specific — cite the exact source document and section
2. Include table names when discussing transformations
3. Mention the data layer context
4. If you're not confident, say so — don't hallucinate
5. Format responses with markdown for readability
"""


SUPERVISOR_AGENT_PROMPT = """You are the Supervisor for the eMobility DataPlatform Copilot.

Your job is to:
1. UNDERSTAND the user's intent from their natural language query
2. ROUTE to the correct sub-agent
3. HANDLE multi-turn context using conversation history

Intent categories and routing:
- KNOWLEDGE_LOOKUP → Knowledge Agent
  Triggers: "how does", "what is", "explain", "describe", documentation questions,
  pipeline architecture, transformation logic, business rules

- STRUCTURED_QUERY → Genie SQL Agent
  Triggers: "how many", "count", "total", "average", "trend", "last month",
  metrics, KPIs, data queries with numbers

- HYBRID → Both Knowledge Agent + Genie SQL Agent
  Triggers: "why did X change", queries needing both data + explanation

Rules:
- Always classify intent FIRST before routing
- If confidence < 0.6, ask a clarifying question instead of guessing
- For HYBRID queries, call both agents and merge results
- Include last 5 conversation turns for context resolution
- Return structured JSON: {"intent": "...", "confidence": 0.XX, "agents": [...]}
"""


RESPONSE_COMPOSER_PROMPT = """You are the Response Composer for the eMobility DataPlatform Copilot.

Your role: Take retrieved knowledge chunks and synthesize a clear, accurate answer.

Rules:
1. Answer the user's question directly — don't repeat the question back
2. Use ONLY the provided chunks — never make up information
3. Cite your sources: [Source: filename §section_name]
4. If chunks are insufficient to fully answer, say what you know and what's missing
5. Format with markdown: use headers, bullet points, code blocks as appropriate
6. Keep answers concise but complete — aim for 200-400 words
7. When discussing transformations, include relevant column names and logic
8. When multiple chunks cover the same topic, synthesize — don't repeat
"""


QUERY_UNDERSTANDING_PROMPT = """You are a query parser for the eMobility DataPlatform.

Given a user query, extract structured metadata to enable deterministic document retrieval.

Known source systems: driivz, enovos, spirii, uberall
Known data layers: landing, raw, euh
Known section types: path, notebook_purpose, data_layer, column_transformations, transformation_steps, business_rules, deduplication_logic, join_logic, error_handling

Return ONLY valid JSON:
{
    "source_name": "<source system or null>",
    "data_layer": "<landing|raw|euh or null>",
    "section_type": "<section name or null>",
    "tables_mentioned": ["<table names if any>"],
    "search_terms": ["<key terms for search>"],
    "confidence": 0.XX
}

Examples:
- "How does Driivz EUH transform sessions?" → {"source_name": "driivz", "data_layer": "euh", "section_type": "transformation_steps", "tables_mentioned": ["sessions"], "search_terms": ["transform", "sessions"], "confidence": 0.95}
- "What business rules apply to Uberall data?" → {"source_name": "uberall", "data_layer": null, "section_type": "business_rules", "tables_mentioned": [], "search_terms": ["business rules"], "confidence": 0.85}
- "What deduplication logic is used in Spirii raw layer?" → {"source_name": "spirii", "data_layer": "raw", "section_type": "deduplication_logic", "tables_mentioned": [], "search_terms": ["deduplication"], "confidence": 0.9}
"""

print("✅ Agent prompts defined as Python constants:")
print(f"   KNOWLEDGE_AGENT_PROMPT     ({len(KNOWLEDGE_AGENT_PROMPT)} chars)")
print(f"   SUPERVISOR_AGENT_PROMPT    ({len(SUPERVISOR_AGENT_PROMPT)} chars)")
print(f"   RESPONSE_COMPOSER_PROMPT   ({len(RESPONSE_COMPOSER_PROMPT)} chars)")
print(f"   QUERY_UNDERSTANDING_PROMPT ({len(QUERY_UNDERSTANDING_PROMPT)} chars)")

# COMMAND ----------

# MAGIC %md
# MAGIC ## ✅ Verification

# COMMAND ----------

# MAGIC %sql
# MAGIC SHOW TABLES IN `emobility-uc-dev`.`sandbox-emobility` LIKE 'copilot_*';

# COMMAND ----------

# MAGIC %sql
# MAGIC DESCRIBE TABLE `emobility-uc-dev`.`sandbox-emobility`.copilot_knowledge_chunks;

# COMMAND ----------

# MAGIC %sql
# MAGIC DESCRIBE TABLE `emobility-uc-dev`.`sandbox-emobility`.copilot_conversations;

# COMMAND ----------

# MAGIC %md
# MAGIC ## ✅ Activity 2 Complete
# MAGIC
# MAGIC **Created:**
# MAGIC - `copilot_knowledge_chunks` — enriched chunks table for RAG
# MAGIC - `copilot_conversations` — conversation history + analytics
# MAGIC - Agent prompts as Python constants (no Volume needed)
# MAGIC
# MAGIC **Next → Activity 3: Knowledge Ingestion Pipeline**
